on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: echo '::set-output name=NODE_VERSION::$(node -v)'
        id: get-node-version
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${steps.get-node-version.outputs.NODE_VERSIOn}-${{ hashFiles('package-lock.json') }}
      - shell: bash
        run: |
          if [[ -d node_modules ]]; then
            npm ci
          fi
      - run: npm run build
